
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build & Deploy WebApp

env:
  ARTIFACT_NAME: csye6225-webapp-${{ github.GITHUB_SHA}}.zip
  CODEDEPLOY_APPLICATION_NAME: csye6225-webapp
  CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME: csye6225-webapp-deployment
  AWS_REGION: us-east-1

on:
  push:
    branches: [ mvn-workflow , hw6]
  pull_request:
    branches: [ master ]

jobs:
  ci_cd:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v11
      with:
        java-version: 1.8
    
    - name: Build with Maven
      run: |
        echo "${{env.ARTIFACT_NAME}}"
        pwd
        ls
        mvn -B package --file pom.xml
        pwd
        ls -al

    # steps:
    # - uses: actions/checkout@v2
    # - name: Set up JDK 11
    #   uses: actions/setup-java@v1
    #   with:
    #     java-version: '11'
    # - name: Run all unit test Build with Maven
    #   run: mvn -B package --file webapp/pom.xml
    # - name: Upload to S3
    #   run : bash scripts/release.sh ${{secrets.AWS_Bucket_Name}} "webapp/webapp-0.0.1-SNAPSHOT.jar" ${{secrets.AWSACCESSKEYID}} ${{secrets.AWSSECRETKEY}} "webapp/target/webapp-0.0.1-SNAPSHOT.jar"

      